---
- hosts: all
  tasks:
    - name: Install Python3
      become: yes
      apt: name=python3 update_cache=yes state=latest

    - name: Install Git package
      become: yes
      apt: name=git update_cache=yes state=latest

    - name: ensure apache is at the latest version
      become: yes
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      become: yes
      apache2_module: name=rewrite state=present

#    - name: apache2 listen on port {{ app_port }}
#      become: yes
#      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen {{ app_port }}" state=present

#    - name: apache2 virtualhost on port {{ app_port }}
#      become: yes
#      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:{{ app_port }}>" state=present

    - name: remove default Apache port.conf
      become: yes
      file:
        path: /etc/apache2/ports.conf
        state: absent

    - name: remove default Apache default.conf
      become: yes
      file:
        path: /etc/apache2/sites-available/000-default.conf
        state: absent

    - name: Create Apache port.conf
      become: yes
      template:
        src: templates/ports.conf.j2
        dest: /etc/apache2/ports.conf

    - name: Create Apache default.conf
      become: yes
      template:
        src: templates/000-default.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf

    - name: remove default website directory
      become: yes
      file:
        path: /var/www/html
        state: absent

    - name: Git checkout website
      become: yes
      git:
        repo: "{{ app_repo }}"
        dest: /var/www/html
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      become: yes
      service: name=apache2 state=restarted
